Feature/user auth
S2GBird/.github pull request #21
Opened 2023-10-30 19:44 UTC by Fledtrain

2023-10-31 16:16 UTC, ItsJonasL commented on backend/package.json
would it be possible to include Helmet since we are using Express? I read somewhere that helmet will help protect against web vulnerabilities by setting HTTP headers appropriately.

2023-10-31 16:17 UTC, ItsJonasL commented on backend/package.json
Maybe a body-parser too since we have POST request

2023-10-31 16:23 UTC, ItsJonasL commented on backend/app.js
>  app.get('/login', async function (req, res) { })
aren't we using express-openid-connect, then wouldn't this handle be not in use because that library should handle login route once fully set up?

2023-10-31 16:24 UTC, ItsJonasL requested changes
Left some comments on the code, and maybe error logging should be included somewhere?

2023-10-31 16:29 UTC, ItsJonasL commented on backend/app.js
Looks good, but I would suggest adding in an error-handling middleware

2023-10-31 16:39 UTC, ItsJonasL requested changes

2023-10-31 16:39 UTC, ItsJonasL commented on backend/controllers/auth.controller.js
> +    res.cookie('login_token', token, { httpOnly: true, expires }).sendStatus(200)
I think we can add in secure:true for security and  SameSite: 'Strict' for CSRF?

2023-10-31 16:39 UTC, ItsJonasL commented on backend/controllers/auth.controller.js
> +require('dotenv').config()
wait don't we need to make a .gitignore file so .env files don't get exposed?

2023-10-31 16:39 UTC, ItsJonasL commented on backend/models/userModel.js
> +    unique: true
Oh maybe we can add in a basic email validation?

2023-10-31 18:07 UTC, DerrickMac requested changes
Thank you for your work Fledtrain! Please see comments regarding the /register and /login routes.

2023-10-31 18:07 UTC, DerrickMac commented on backend/controllers/auth.controller.js
> +    res.status(500).json({ message: 'Internal server error' })
passport.js has an authenticate() which checks passwords and handles redirections based on failure. What I don't know is how the jwt is handled behind the scenes of the authenticate method.

if authenticate handles sending a jwt, then we don't need to do this ourselves, but that is something we can figure out. If authenticate doesn't handle sending jwts then we need to figure out how to redirect the user to their personal dashboard while sending a jwt as well.

Below is what I had used in my testing in my own app.js so it won't work inside your auth.controller.js.

app.post('/login', passport.authenticate('local', { failureRedirect: '/login', failureMessage: true }), async function(req, res) {
  try{
    res.redirect('/' + req.user.username)
  }
  catch (error) {
    console.log(error);
  }
});

2023-11-02 19:39 UTC, DorisSanchez-Velasquez requested changes

2023-11-02 19:39 UTC, DorisSanchez-Velasquez commented on backend/app.js
> +// app.post('/register', async (req, res) => {
Make sure to clean up all commented out code unless it is super important to be kept for the functionality of future sprints :) (helps prevent clutter within the files as they get bigger)

2023-11-02 20:17 UTC, closed without merging