Add files via upload
S2GBird/.github pull request #29
Opened 2023-11-10 06:25 UTC by Slouis07

aboutuspage base example

2023-11-15 14:35 UTC, ItsJonasL requested changes
please implement the changes because its failing on the linter. I have included the code that should be changed.

2023-11-15 14:35 UTC, ItsJonasL commented on aboutuspage.html
> +                  <li><a href="#">Terms & Conditions</a></li>
( li><a href="#">Terms &amp; Conditions</a></li ) 


use this instead the current code as that is triggering the linter to fail it.

2023-11-15 14:35 UTC, ItsJonasL commented on aboutus.css
> +    font-family: 'Arial', sans-serif;
ya got to remove '' that is around Arial.

2023-11-17 15:17 UTC, DorisSanchez-Velasquez requested changes
Great Work! Change requested in terms of making the html and css files adhere to React .jsx files.

2023-11-17 15:17 UTC, DorisSanchez-Velasquez commented on aboutuspage.html
> +<body>
Awesome Work! Looks pretty good in terms of code! :)

Change Requested:
We're using React (.jsx) files in the main frontend code so a lot of this html and CSS can be transferred to the React files and prevent people from having to initiialize the <head> tags on every file. 

How To Implement Change:
Under the Pages folder, create another folder for AboutUs and create a .jsx file and a .module.css file and move all the code you in the <body> tag of this file into the .jsx file. Same thing with the .module.css file.  Checkout the Example.jsx file if you need help structuring out the .jsx file.

Reasoning:
React files are alot more flexible in terms of being able to implement functionality within the same files where you're inputting html structures. Essentially, React is a framework that combines everything you would put in a CSS, HTML, and JS file. :)

2023-11-17 15:17 UTC, DorisSanchez-Velasquez commented on aboutus.css
> +body {
Same change requested as the html file. Transfer all styling to a .module.css file within an AboutUs Folder. :)

2023-11-17 21:54 UTC, DerrickMac commented
Closing pull request as updates to this were done on PR #33

2023-11-17 21:54 UTC, closed without merging