404 Not Found Implemented
S2GBird/.github pull request #53
Opened 2023-12-29 21:47 UTC by SamirZelaya

- 404 Not Found Page is functionable
- "Back to Home" button links to dashboard for now
- Also, trying to see if I did the pull request correctly with no issues to main branch.

2023-12-29 22:59 UTC, v74c63t commented
What you have right now is running into some issues with the linter so you have to click on `Details` and scroll down to check what's causing issues and fix them (the error about the github token can be ignored). The linter usually takes a few minutes to run completely so after creating a pull request or making any commits to the branch in the pull request, you have to check back in a few minutes to see if it fails the linter check and make changes accordingly if it does. Below, I have included a screenshot of the issues that the linter is complaining about, but in the future, you can click on `Details` to view it, if you can't find it, make sure `Show all checks` have already been toggled and it should appear.
<img width="732" alt="Screenshot 2023-12-29 at 2 36 18 PM" src="https://github.com/S2GBird/.github/assets/78942001/de2bfd35-cf18-4728-bbaa-075532df4094">
Once you fixed all of those, you just have to wait for your pull request to be reviewed and merged (however you may need to merge some code or resolve conflicts for this branch if other pull requests are approved before yours is). There is probably a command that can automatically fix these for you that you can find somewhere in the discord, but I usually just manually fix these.

2023-12-29 23:56 UTC, ItsJonasL commented
do the standard --fix in CMD and not the PowerShell that VSstudio auto prompts you into. Be sure to install the dependencies for it first too after you fix the issues.

2024-01-05 18:25 UTC, DorisSanchez-Velasquez commented on frontend/src/Pages/App/App.jsx
> +          <Route path='/*' element={<NotFound />} />
switch path link to just *

2024-01-05 18:26 UTC, DorisSanchez-Velasquez requested changes
Looks really good!! :) Just a small request to change the name of the CSS file to .module.css to make sure that any css from this file doesn't leak into the other ones. Also, to fix the linter issue: just run the command: **npx standard --fix**

2024-01-05 21:48 UTC, v74c63t requested changes

2024-01-05 21:48 UTC, v74c63t commented on frontend/src/Pages/App/App.jsx
There were some changes that were merged into App.jsx so make sure to resolve the merge conflicts there. Be careful to not completely overwrite the file with what you have since it would cause issues with the auth context. Just add your import and route to what is already in App.jsx. Other than that, everything else looks good.

2024-01-11 02:16 UTC, ItsJonasL requested changes
You need to implement above changes, and also the merge issue

2024-01-19 19:00 UTC, closed without merging