add routes to like/unlike comments
S2GBird/.github pull request #63
Opened 2024-01-30 23:51 UTC by Goketech

2024-02-23 22:35 UTC, ItsJonasL approved these changes
Looks good for now. We can work with this.

2024-02-23 22:40 UTC, v74c63t requested changes
Can you add a route that can allow front end to check if a user liked a post or not so it can be displayed correctly on front end. This is so we don't have to go through calling add like to comment to check if the like exists or not and having to unlike afterwards to decide whether the comment should be displayed as liked or not when it first loads in. This should be a fairly simple to add.

2024-02-28 05:22 UTC, Goketech commented
> Can you add a route that can allow front end to check if a user liked a post or not so it can be displayed correctly on front end. This is so we don't have to go through calling add like to comment to check if the like exists or not and having to unlike afterwards to decide whether the comment should be displayed as liked or not when it first loads in. This should be a fairly simple to add.

I have added routes that addresses this issue

2024-02-28 05:33 UTC, v74c63t approved these changes

2024-02-28 14:24 UTC, merged